esphome:
  name: pir_test
  platform: ESP8266
  board: nodemcu

wifi:
  ssid: !secret wifi_ssid #change to your own
  password: !secret wifi_pass # change to your own
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "tessing Fallback Hotspot"
    password: "TPIR1234"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: D1
      mode: INPUT_PULLUP
    name: motion_zone1
  - platform: gpio
    pin:
      number: D2
      mode: INPUT_PULLUP
    name: motion_zone2
  - platform: gpio
    pin:
      number: D5
      mode: INPUT_PULLUP
    name: motion_zone3
  - platform: gpio
    pin:
      number: D6
      mode: INPUT_PULLUP
    name: motion_zone4
    
  - platform: gpio
    pin:
      number: D7
      mode: INPUT_PULLUP
    name: tamper
    
